/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AuditLog } from "./AuditLog";
import { AuditLogCountArgs } from "./AuditLogCountArgs";
import { AuditLogFindManyArgs } from "./AuditLogFindManyArgs";
import { AuditLogFindUniqueArgs } from "./AuditLogFindUniqueArgs";
import { CreateAuditLogArgs } from "./CreateAuditLogArgs";
import { UpdateAuditLogArgs } from "./UpdateAuditLogArgs";
import { DeleteAuditLogArgs } from "./DeleteAuditLogArgs";
import { AuditLogService } from "../auditLog.service";
@graphql.Resolver(() => AuditLog)
export class AuditLogResolverBase {
  constructor(protected readonly service: AuditLogService) {}

  async _auditLogsMeta(
    @graphql.Args() args: AuditLogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AuditLog])
  async auditLogs(
    @graphql.Args() args: AuditLogFindManyArgs
  ): Promise<AuditLog[]> {
    return this.service.auditLogs(args);
  }

  @graphql.Query(() => AuditLog, { nullable: true })
  async auditLog(
    @graphql.Args() args: AuditLogFindUniqueArgs
  ): Promise<AuditLog | null> {
    const result = await this.service.auditLog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AuditLog)
  async createAuditLog(
    @graphql.Args() args: CreateAuditLogArgs
  ): Promise<AuditLog> {
    return await this.service.createAuditLog({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => AuditLog)
  async updateAuditLog(
    @graphql.Args() args: UpdateAuditLogArgs
  ): Promise<AuditLog | null> {
    try {
      return await this.service.updateAuditLog({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AuditLog)
  async deleteAuditLog(
    @graphql.Args() args: DeleteAuditLogArgs
  ): Promise<AuditLog | null> {
    try {
      return await this.service.deleteAuditLog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
