/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, AccountPool as PrismaAccountPool } from "@prisma/client";

export class AccountPoolServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AccountPoolCountArgs, "select">
  ): Promise<number> {
    return this.prisma.accountPool.count(args);
  }

  async accountPools(
    args: Prisma.AccountPoolFindManyArgs
  ): Promise<PrismaAccountPool[]> {
    return this.prisma.accountPool.findMany(args);
  }
  async accountPool(
    args: Prisma.AccountPoolFindUniqueArgs
  ): Promise<PrismaAccountPool | null> {
    return this.prisma.accountPool.findUnique(args);
  }
  async createAccountPool(
    args: Prisma.AccountPoolCreateArgs
  ): Promise<PrismaAccountPool> {
    return this.prisma.accountPool.create(args);
  }
  async updateAccountPool(
    args: Prisma.AccountPoolUpdateArgs
  ): Promise<PrismaAccountPool> {
    return this.prisma.accountPool.update(args);
  }
  async deleteAccountPool(
    args: Prisma.AccountPoolDeleteArgs
  ): Promise<PrismaAccountPool> {
    return this.prisma.accountPool.delete(args);
  }
}
