/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AccountPoolService } from "../accountPool.service";
import { AccountPoolCreateInput } from "./AccountPoolCreateInput";
import { AccountPool } from "./AccountPool";
import { AccountPoolFindManyArgs } from "./AccountPoolFindManyArgs";
import { AccountPoolWhereUniqueInput } from "./AccountPoolWhereUniqueInput";
import { AccountPoolUpdateInput } from "./AccountPoolUpdateInput";

export class AccountPoolControllerBase {
  constructor(protected readonly service: AccountPoolService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AccountPool })
  async createAccountPool(
    @common.Body() data: AccountPoolCreateInput
  ): Promise<AccountPool> {
    return await this.service.createAccountPool({
      data: data,
      select: {
        assignedAt: true,
        assignedToUserId: true,
        createdAt: true,
        id: true,
        notes: true,
        passwordEnc: true,
        status: true,
        totpSecretEnc: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AccountPool] })
  @ApiNestedQuery(AccountPoolFindManyArgs)
  async accountPools(@common.Req() request: Request): Promise<AccountPool[]> {
    const args = plainToClass(AccountPoolFindManyArgs, request.query);
    return this.service.accountPools({
      ...args,
      select: {
        assignedAt: true,
        assignedToUserId: true,
        createdAt: true,
        id: true,
        notes: true,
        passwordEnc: true,
        status: true,
        totpSecretEnc: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AccountPool })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async accountPool(
    @common.Param() params: AccountPoolWhereUniqueInput
  ): Promise<AccountPool | null> {
    const result = await this.service.accountPool({
      where: params,
      select: {
        assignedAt: true,
        assignedToUserId: true,
        createdAt: true,
        id: true,
        notes: true,
        passwordEnc: true,
        status: true,
        totpSecretEnc: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AccountPool })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAccountPool(
    @common.Param() params: AccountPoolWhereUniqueInput,
    @common.Body() data: AccountPoolUpdateInput
  ): Promise<AccountPool | null> {
    try {
      return await this.service.updateAccountPool({
        where: params,
        data: data,
        select: {
          assignedAt: true,
          assignedToUserId: true,
          createdAt: true,
          id: true,
          notes: true,
          passwordEnc: true,
          status: true,
          totpSecretEnc: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AccountPool })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAccountPool(
    @common.Param() params: AccountPoolWhereUniqueInput
  ): Promise<AccountPool | null> {
    try {
      return await this.service.deleteAccountPool({
        where: params,
        select: {
          assignedAt: true,
          assignedToUserId: true,
          createdAt: true,
          id: true,
          notes: true,
          passwordEnc: true,
          status: true,
          totpSecretEnc: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
