/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AccountPool } from "./AccountPool";
import { AccountPoolCountArgs } from "./AccountPoolCountArgs";
import { AccountPoolFindManyArgs } from "./AccountPoolFindManyArgs";
import { AccountPoolFindUniqueArgs } from "./AccountPoolFindUniqueArgs";
import { CreateAccountPoolArgs } from "./CreateAccountPoolArgs";
import { UpdateAccountPoolArgs } from "./UpdateAccountPoolArgs";
import { DeleteAccountPoolArgs } from "./DeleteAccountPoolArgs";
import { AccountPoolService } from "../accountPool.service";
@graphql.Resolver(() => AccountPool)
export class AccountPoolResolverBase {
  constructor(protected readonly service: AccountPoolService) {}

  async _accountPoolsMeta(
    @graphql.Args() args: AccountPoolCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AccountPool])
  async accountPools(
    @graphql.Args() args: AccountPoolFindManyArgs
  ): Promise<AccountPool[]> {
    return this.service.accountPools(args);
  }

  @graphql.Query(() => AccountPool, { nullable: true })
  async accountPool(
    @graphql.Args() args: AccountPoolFindUniqueArgs
  ): Promise<AccountPool | null> {
    const result = await this.service.accountPool(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AccountPool)
  async createAccountPool(
    @graphql.Args() args: CreateAccountPoolArgs
  ): Promise<AccountPool> {
    return await this.service.createAccountPool({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => AccountPool)
  async updateAccountPool(
    @graphql.Args() args: UpdateAccountPoolArgs
  ): Promise<AccountPool | null> {
    try {
      return await this.service.updateAccountPool({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AccountPool)
  async deleteAccountPool(
    @graphql.Args() args: DeleteAccountPoolArgs
  ): Promise<AccountPool | null> {
    try {
      return await this.service.deleteAccountPool(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
