/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { EntitlementService } from "../entitlement.service";
import { EntitlementCreateInput } from "./EntitlementCreateInput";
import { Entitlement } from "./Entitlement";
import { EntitlementFindManyArgs } from "./EntitlementFindManyArgs";
import { EntitlementWhereUniqueInput } from "./EntitlementWhereUniqueInput";
import { EntitlementUpdateInput } from "./EntitlementUpdateInput";
import { TotpControlFindManyArgs } from "../../totpControl/base/TotpControlFindManyArgs";
import { TotpControl } from "../../totpControl/base/TotpControl";
import { TotpControlWhereUniqueInput } from "../../totpControl/base/TotpControlWhereUniqueInput";

export class EntitlementControllerBase {
  constructor(protected readonly service: EntitlementService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Entitlement })
  async createEntitlement(
    @common.Body() data: EntitlementCreateInput
  ): Promise<Entitlement> {
    return await this.service.createEntitlement({
      data: {
        ...data,

        product: data.product
          ? {
              connect: data.product,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        accountId: true,
        createdAt: true,
        expiryDate: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        purchaseDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Entitlement] })
  @ApiNestedQuery(EntitlementFindManyArgs)
  async entitlements(@common.Req() request: Request): Promise<Entitlement[]> {
    const args = plainToClass(EntitlementFindManyArgs, request.query);
    return this.service.entitlements({
      ...args,
      select: {
        accountId: true,
        createdAt: true,
        expiryDate: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        purchaseDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Entitlement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async entitlement(
    @common.Param() params: EntitlementWhereUniqueInput
  ): Promise<Entitlement | null> {
    const result = await this.service.entitlement({
      where: params,
      select: {
        accountId: true,
        createdAt: true,
        expiryDate: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        purchaseDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Entitlement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateEntitlement(
    @common.Param() params: EntitlementWhereUniqueInput,
    @common.Body() data: EntitlementUpdateInput
  ): Promise<Entitlement | null> {
    try {
      return await this.service.updateEntitlement({
        where: params,
        data: {
          ...data,

          product: data.product
            ? {
                connect: data.product,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          accountId: true,
          createdAt: true,
          expiryDate: true,
          id: true,

          product: {
            select: {
              id: true,
            },
          },

          purchaseDate: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Entitlement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteEntitlement(
    @common.Param() params: EntitlementWhereUniqueInput
  ): Promise<Entitlement | null> {
    try {
      return await this.service.deleteEntitlement({
        where: params,
        select: {
          accountId: true,
          createdAt: true,
          expiryDate: true,
          id: true,

          product: {
            select: {
              id: true,
            },
          },

          purchaseDate: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/totpControls")
  @ApiNestedQuery(TotpControlFindManyArgs)
  async findTotpControls(
    @common.Req() request: Request,
    @common.Param() params: EntitlementWhereUniqueInput
  ): Promise<TotpControl[]> {
    const query = plainToClass(TotpControlFindManyArgs, request.query);
    const results = await this.service.findTotpControls(params.id, {
      ...query,
      select: {
        blockedUntil: true,
        createdAt: true,
        deviceHash: true,

        entitlement: {
          select: {
            id: true,
          },
        },

        flags: true,
        id: true,
        totpCount7d: true,
        totpCountDay: true,
        totpLastIssuedAt: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/totpControls")
  async connectTotpControls(
    @common.Param() params: EntitlementWhereUniqueInput,
    @common.Body() body: TotpControlWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      totpControls: {
        connect: body,
      },
    };
    await this.service.updateEntitlement({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/totpControls")
  async updateTotpControls(
    @common.Param() params: EntitlementWhereUniqueInput,
    @common.Body() body: TotpControlWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      totpControls: {
        set: body,
      },
    };
    await this.service.updateEntitlement({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/totpControls")
  async disconnectTotpControls(
    @common.Param() params: EntitlementWhereUniqueInput,
    @common.Body() body: TotpControlWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      totpControls: {
        disconnect: body,
      },
    };
    await this.service.updateEntitlement({
      where: params,
      data,
      select: { id: true },
    });
  }
}
