/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Entitlement as PrismaEntitlement,
  TotpControl as PrismaTotpControl,
  Product as PrismaProduct,
  User as PrismaUser,
} from "@prisma/client";

export class EntitlementServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.EntitlementCountArgs, "select">
  ): Promise<number> {
    return this.prisma.entitlement.count(args);
  }

  async entitlements(
    args: Prisma.EntitlementFindManyArgs
  ): Promise<PrismaEntitlement[]> {
    return this.prisma.entitlement.findMany(args);
  }
  async entitlement(
    args: Prisma.EntitlementFindUniqueArgs
  ): Promise<PrismaEntitlement | null> {
    return this.prisma.entitlement.findUnique(args);
  }
  async createEntitlement(
    args: Prisma.EntitlementCreateArgs
  ): Promise<PrismaEntitlement> {
    return this.prisma.entitlement.create(args);
  }
  async updateEntitlement(
    args: Prisma.EntitlementUpdateArgs
  ): Promise<PrismaEntitlement> {
    return this.prisma.entitlement.update(args);
  }
  async deleteEntitlement(
    args: Prisma.EntitlementDeleteArgs
  ): Promise<PrismaEntitlement> {
    return this.prisma.entitlement.delete(args);
  }

  async findTotpControls(
    parentId: string,
    args: Prisma.TotpControlFindManyArgs
  ): Promise<PrismaTotpControl[]> {
    return this.prisma.entitlement
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .totpControls(args);
  }

  async getProduct(parentId: string): Promise<PrismaProduct | null> {
    return this.prisma.entitlement
      .findUnique({
        where: { id: parentId },
      })
      .product();
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.entitlement
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
