/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Entitlement } from "./Entitlement";
import { EntitlementCountArgs } from "./EntitlementCountArgs";
import { EntitlementFindManyArgs } from "./EntitlementFindManyArgs";
import { EntitlementFindUniqueArgs } from "./EntitlementFindUniqueArgs";
import { CreateEntitlementArgs } from "./CreateEntitlementArgs";
import { UpdateEntitlementArgs } from "./UpdateEntitlementArgs";
import { DeleteEntitlementArgs } from "./DeleteEntitlementArgs";
import { TotpControlFindManyArgs } from "../../totpControl/base/TotpControlFindManyArgs";
import { TotpControl } from "../../totpControl/base/TotpControl";
import { Product } from "../../product/base/Product";
import { User } from "../../user/base/User";
import { EntitlementService } from "../entitlement.service";
@graphql.Resolver(() => Entitlement)
export class EntitlementResolverBase {
  constructor(protected readonly service: EntitlementService) {}

  async _entitlementsMeta(
    @graphql.Args() args: EntitlementCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Entitlement])
  async entitlements(
    @graphql.Args() args: EntitlementFindManyArgs
  ): Promise<Entitlement[]> {
    return this.service.entitlements(args);
  }

  @graphql.Query(() => Entitlement, { nullable: true })
  async entitlement(
    @graphql.Args() args: EntitlementFindUniqueArgs
  ): Promise<Entitlement | null> {
    const result = await this.service.entitlement(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Entitlement)
  async createEntitlement(
    @graphql.Args() args: CreateEntitlementArgs
  ): Promise<Entitlement> {
    return await this.service.createEntitlement({
      ...args,
      data: {
        ...args.data,

        product: args.data.product
          ? {
              connect: args.data.product,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Entitlement)
  async updateEntitlement(
    @graphql.Args() args: UpdateEntitlementArgs
  ): Promise<Entitlement | null> {
    try {
      return await this.service.updateEntitlement({
        ...args,
        data: {
          ...args.data,

          product: args.data.product
            ? {
                connect: args.data.product,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Entitlement)
  async deleteEntitlement(
    @graphql.Args() args: DeleteEntitlementArgs
  ): Promise<Entitlement | null> {
    try {
      return await this.service.deleteEntitlement(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [TotpControl], { name: "totpControls" })
  async findTotpControls(
    @graphql.Parent() parent: Entitlement,
    @graphql.Args() args: TotpControlFindManyArgs
  ): Promise<TotpControl[]> {
    const results = await this.service.findTotpControls(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Product, {
    nullable: true,
    name: "product",
  })
  async getProduct(
    @graphql.Parent() parent: Entitlement
  ): Promise<Product | null> {
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Entitlement): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
