/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { EntitlementFindManyArgs } from "../../entitlement/base/EntitlementFindManyArgs";
import { Entitlement } from "../../entitlement/base/Entitlement";
import { EntitlementWhereUniqueInput } from "../../entitlement/base/EntitlementWhereUniqueInput";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { OrderWhereUniqueInput } from "../../order/base/OrderWhereUniqueInput";
import { TotpControlFindManyArgs } from "../../totpControl/base/TotpControlFindManyArgs";
import { TotpControl } from "../../totpControl/base/TotpControl";
import { TotpControlWhereUniqueInput } from "../../totpControl/base/TotpControlWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: data,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastLoginAt: true,
        lastName: true,
        passwordHash: true,
        role: true,
        roles: true,
        telegramChatId: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastLoginAt: true,
        lastName: true,
        passwordHash: true,
        role: true,
        roles: true,
        telegramChatId: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastLoginAt: true,
        lastName: true,
        passwordHash: true,
        role: true,
        roles: true,
        telegramChatId: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastLoginAt: true,
          lastName: true,
          passwordHash: true,
          role: true,
          roles: true,
          telegramChatId: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastLoginAt: true,
          lastName: true,
          passwordHash: true,
          role: true,
          roles: true,
          telegramChatId: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/entitlements")
  @ApiNestedQuery(EntitlementFindManyArgs)
  async findEntitlements(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Entitlement[]> {
    const query = plainToClass(EntitlementFindManyArgs, request.query);
    const results = await this.service.findEntitlements(params.id, {
      ...query,
      select: {
        accountId: true,
        createdAt: true,
        expiryDate: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        purchaseDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/entitlements")
  async connectEntitlements(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: EntitlementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      entitlements: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/entitlements")
  async updateEntitlements(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: EntitlementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      entitlements: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/entitlements")
  async disconnectEntitlements(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: EntitlementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      entitlements: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/orders")
  @ApiNestedQuery(OrderFindManyArgs)
  async findOrders(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Order[]> {
    const query = plainToClass(OrderFindManyArgs, request.query);
    const results = await this.service.findOrders(params.id, {
      ...query,
      select: {
        createdAt: true,
        currency: true,
        deliveredAt: true,
        id: true,
        invoiceId: true,
        paymentIntentId: true,
        paymentProvider: true,
        status: true,
        total: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/orders")
  async connectOrders(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/orders")
  async updateOrders(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/orders")
  async disconnectOrders(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/totpControls")
  @ApiNestedQuery(TotpControlFindManyArgs)
  async findTotpControls(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<TotpControl[]> {
    const query = plainToClass(TotpControlFindManyArgs, request.query);
    const results = await this.service.findTotpControls(params.id, {
      ...query,
      select: {
        blockedUntil: true,
        createdAt: true,
        deviceHash: true,

        entitlement: {
          select: {
            id: true,
          },
        },

        flags: true,
        id: true,
        totpCount7d: true,
        totpCountDay: true,
        totpLastIssuedAt: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/totpControls")
  async connectTotpControls(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TotpControlWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      totpControls: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/totpControls")
  async updateTotpControls(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TotpControlWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      totpControls: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/totpControls")
  async disconnectTotpControls(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TotpControlWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      totpControls: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
