/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TotpControlService } from "../totpControl.service";
import { TotpControlCreateInput } from "./TotpControlCreateInput";
import { TotpControl } from "./TotpControl";
import { TotpControlFindManyArgs } from "./TotpControlFindManyArgs";
import { TotpControlWhereUniqueInput } from "./TotpControlWhereUniqueInput";
import { TotpControlUpdateInput } from "./TotpControlUpdateInput";

export class TotpControlControllerBase {
  constructor(protected readonly service: TotpControlService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TotpControl })
  async createTotpControl(
    @common.Body() data: TotpControlCreateInput
  ): Promise<TotpControl> {
    return await this.service.createTotpControl({
      data: {
        ...data,

        entitlement: data.entitlement
          ? {
              connect: data.entitlement,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        blockedUntil: true,
        createdAt: true,
        deviceHash: true,

        entitlement: {
          select: {
            id: true,
          },
        },

        flags: true,
        id: true,
        totpCount7d: true,
        totpCountDay: true,
        totpLastIssuedAt: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TotpControl] })
  @ApiNestedQuery(TotpControlFindManyArgs)
  async totpControls(@common.Req() request: Request): Promise<TotpControl[]> {
    const args = plainToClass(TotpControlFindManyArgs, request.query);
    return this.service.totpControls({
      ...args,
      select: {
        blockedUntil: true,
        createdAt: true,
        deviceHash: true,

        entitlement: {
          select: {
            id: true,
          },
        },

        flags: true,
        id: true,
        totpCount7d: true,
        totpCountDay: true,
        totpLastIssuedAt: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TotpControl })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async totpControl(
    @common.Param() params: TotpControlWhereUniqueInput
  ): Promise<TotpControl | null> {
    const result = await this.service.totpControl({
      where: params,
      select: {
        blockedUntil: true,
        createdAt: true,
        deviceHash: true,

        entitlement: {
          select: {
            id: true,
          },
        },

        flags: true,
        id: true,
        totpCount7d: true,
        totpCountDay: true,
        totpLastIssuedAt: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TotpControl })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTotpControl(
    @common.Param() params: TotpControlWhereUniqueInput,
    @common.Body() data: TotpControlUpdateInput
  ): Promise<TotpControl | null> {
    try {
      return await this.service.updateTotpControl({
        where: params,
        data: {
          ...data,

          entitlement: data.entitlement
            ? {
                connect: data.entitlement,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          blockedUntil: true,
          createdAt: true,
          deviceHash: true,

          entitlement: {
            select: {
              id: true,
            },
          },

          flags: true,
          id: true,
          totpCount7d: true,
          totpCountDay: true,
          totpLastIssuedAt: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TotpControl })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTotpControl(
    @common.Param() params: TotpControlWhereUniqueInput
  ): Promise<TotpControl | null> {
    try {
      return await this.service.deleteTotpControl({
        where: params,
        select: {
          blockedUntil: true,
          createdAt: true,
          deviceHash: true,

          entitlement: {
            select: {
              id: true,
            },
          },

          flags: true,
          id: true,
          totpCount7d: true,
          totpCountDay: true,
          totpLastIssuedAt: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
