/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  TotpControl as PrismaTotpControl,
  Entitlement as PrismaEntitlement,
  User as PrismaUser,
} from "@prisma/client";

export class TotpControlServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.TotpControlCountArgs, "select">
  ): Promise<number> {
    return this.prisma.totpControl.count(args);
  }

  async totpControls(
    args: Prisma.TotpControlFindManyArgs
  ): Promise<PrismaTotpControl[]> {
    return this.prisma.totpControl.findMany(args);
  }
  async totpControl(
    args: Prisma.TotpControlFindUniqueArgs
  ): Promise<PrismaTotpControl | null> {
    return this.prisma.totpControl.findUnique(args);
  }
  async createTotpControl(
    args: Prisma.TotpControlCreateArgs
  ): Promise<PrismaTotpControl> {
    return this.prisma.totpControl.create(args);
  }
  async updateTotpControl(
    args: Prisma.TotpControlUpdateArgs
  ): Promise<PrismaTotpControl> {
    return this.prisma.totpControl.update(args);
  }
  async deleteTotpControl(
    args: Prisma.TotpControlDeleteArgs
  ): Promise<PrismaTotpControl> {
    return this.prisma.totpControl.delete(args);
  }

  async getEntitlement(parentId: string): Promise<PrismaEntitlement | null> {
    return this.prisma.totpControl
      .findUnique({
        where: { id: parentId },
      })
      .entitlement();
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.totpControl
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
