/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TotpControl } from "./TotpControl";
import { TotpControlCountArgs } from "./TotpControlCountArgs";
import { TotpControlFindManyArgs } from "./TotpControlFindManyArgs";
import { TotpControlFindUniqueArgs } from "./TotpControlFindUniqueArgs";
import { CreateTotpControlArgs } from "./CreateTotpControlArgs";
import { UpdateTotpControlArgs } from "./UpdateTotpControlArgs";
import { DeleteTotpControlArgs } from "./DeleteTotpControlArgs";
import { Entitlement } from "../../entitlement/base/Entitlement";
import { User } from "../../user/base/User";
import { TotpControlService } from "../totpControl.service";
@graphql.Resolver(() => TotpControl)
export class TotpControlResolverBase {
  constructor(protected readonly service: TotpControlService) {}

  async _totpControlsMeta(
    @graphql.Args() args: TotpControlCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TotpControl])
  async totpControls(
    @graphql.Args() args: TotpControlFindManyArgs
  ): Promise<TotpControl[]> {
    return this.service.totpControls(args);
  }

  @graphql.Query(() => TotpControl, { nullable: true })
  async totpControl(
    @graphql.Args() args: TotpControlFindUniqueArgs
  ): Promise<TotpControl | null> {
    const result = await this.service.totpControl(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TotpControl)
  async createTotpControl(
    @graphql.Args() args: CreateTotpControlArgs
  ): Promise<TotpControl> {
    return await this.service.createTotpControl({
      ...args,
      data: {
        ...args.data,

        entitlement: args.data.entitlement
          ? {
              connect: args.data.entitlement,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => TotpControl)
  async updateTotpControl(
    @graphql.Args() args: UpdateTotpControlArgs
  ): Promise<TotpControl | null> {
    try {
      return await this.service.updateTotpControl({
        ...args,
        data: {
          ...args.data,

          entitlement: args.data.entitlement
            ? {
                connect: args.data.entitlement,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => TotpControl)
  async deleteTotpControl(
    @graphql.Args() args: DeleteTotpControlArgs
  ): Promise<TotpControl | null> {
    try {
      return await this.service.deleteTotpControl(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Entitlement, {
    nullable: true,
    name: "entitlement",
  })
  async getEntitlement(
    @graphql.Parent() parent: TotpControl
  ): Promise<Entitlement | null> {
    const result = await this.service.getEntitlement(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: TotpControl): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
