/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProductService } from "../product.service";
import { ProductCreateInput } from "./ProductCreateInput";
import { Product } from "./Product";
import { ProductFindManyArgs } from "./ProductFindManyArgs";
import { ProductWhereUniqueInput } from "./ProductWhereUniqueInput";
import { ProductUpdateInput } from "./ProductUpdateInput";
import { EntitlementFindManyArgs } from "../../entitlement/base/EntitlementFindManyArgs";
import { Entitlement } from "../../entitlement/base/Entitlement";
import { EntitlementWhereUniqueInput } from "../../entitlement/base/EntitlementWhereUniqueInput";
import { OrderItemFindManyArgs } from "../../orderItem/base/OrderItemFindManyArgs";
import { OrderItem } from "../../orderItem/base/OrderItem";
import { OrderItemWhereUniqueInput } from "../../orderItem/base/OrderItemWhereUniqueInput";
import { VariantFindManyArgs } from "../../variant/base/VariantFindManyArgs";
import { Variant } from "../../variant/base/Variant";
import { VariantWhereUniqueInput } from "../../variant/base/VariantWhereUniqueInput";

export class ProductControllerBase {
  constructor(protected readonly service: ProductService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Product })
  async createProduct(
    @common.Body() data: ProductCreateInput
  ): Promise<Product> {
    return await this.service.createProduct({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        images: true,
        isSpecialTotpProduct: true,
        meta: true,
        slug: true,
        status: true,
        title: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Product] })
  @ApiNestedQuery(ProductFindManyArgs)
  async products(@common.Req() request: Request): Promise<Product[]> {
    const args = plainToClass(ProductFindManyArgs, request.query);
    return this.service.products({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        images: true,
        isSpecialTotpProduct: true,
        meta: true,
        slug: true,
        status: true,
        title: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async product(
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Product | null> {
    const result = await this.service.product({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        images: true,
        isSpecialTotpProduct: true,
        meta: true,
        slug: true,
        status: true,
        title: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProduct(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() data: ProductUpdateInput
  ): Promise<Product | null> {
    try {
      return await this.service.updateProduct({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          images: true,
          isSpecialTotpProduct: true,
          meta: true,
          slug: true,
          status: true,
          title: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProduct(
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Product | null> {
    try {
      return await this.service.deleteProduct({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          images: true,
          isSpecialTotpProduct: true,
          meta: true,
          slug: true,
          status: true,
          title: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/entitlements")
  @ApiNestedQuery(EntitlementFindManyArgs)
  async findEntitlements(
    @common.Req() request: Request,
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Entitlement[]> {
    const query = plainToClass(EntitlementFindManyArgs, request.query);
    const results = await this.service.findEntitlements(params.id, {
      ...query,
      select: {
        accountId: true,
        createdAt: true,
        expiryDate: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        purchaseDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/entitlements")
  async connectEntitlements(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: EntitlementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      entitlements: {
        connect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/entitlements")
  async updateEntitlements(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: EntitlementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      entitlements: {
        set: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/entitlements")
  async disconnectEntitlements(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: EntitlementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      entitlements: {
        disconnect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/orderItems")
  @ApiNestedQuery(OrderItemFindManyArgs)
  async findOrderItems(
    @common.Req() request: Request,
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<OrderItem[]> {
    const query = plainToClass(OrderItemFindManyArgs, request.query);
    const results = await this.service.findOrderItems(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        meta: true,

        order: {
          select: {
            id: true,
          },
        },

        product: {
          select: {
            id: true,
          },
        },

        qty: true,
        titleSnapshot: true,
        unitPrice: true,
        updatedAt: true,

        variant: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/orderItems")
  async connectOrderItems(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: OrderItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orderItems: {
        connect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/orderItems")
  async updateOrderItems(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: OrderItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orderItems: {
        set: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/orderItems")
  async disconnectOrderItems(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: OrderItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orderItems: {
        disconnect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/variants")
  @ApiNestedQuery(VariantFindManyArgs)
  async findVariants(
    @common.Req() request: Request,
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Variant[]> {
    const query = plainToClass(VariantFindManyArgs, request.query);
    const results = await this.service.findVariants(params.id, {
      ...query,
      select: {
        active: true,
        createdAt: true,
        currency: true,
        id: true,
        name: true,
        price: true,

        product: {
          select: {
            id: true,
          },
        },

        sku: true,
        stock: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/variants")
  async connectVariants(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: VariantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      variants: {
        connect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/variants")
  async updateVariants(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: VariantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      variants: {
        set: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/variants")
  async disconnectVariants(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: VariantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      variants: {
        disconnect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }
}
